name: OreFusion
version: '1.0'
main: com.pyotcho.orefusion.OreFusion
api-version: '1.20'
authors: [ Pyotcho ]

commands:
  rune:
    description: Give a rune to a player
    usage: /rune give <player> <rune>
    permission: rune.give

permissions:
  rune.give:
    description: Perm to give runes
    default: op